### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.release()' on a null object reference

### ISSUE THREAD

**Issue by Marukohe** [Crazy-Marvin/Morse#131]
Hello, I maybe found a bug when using this app.
Just click the place shown in the picture below for several times, and the bug will be triggered.

<img width="413" alt="截屏2022-11-22 12 04 39" src="https://user-images.githubusercontent.com/32957242/203219126-8f3f7570-755b-43a9-854a-8bdbe700692f.png">

Here is the error message:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.release()' on a null object reference
 	at rocks.poopjournal.morse.MainActivity.lambda$setKeySelectedForTelegraph$25$rocks-poopjournal-morse-MainActivity(MainActivity.java:1267)
 	at rocks.poopjournal.morse.MainActivity$$ExternalSyntheticLambda9.run(Unknown Source:2)
 	at android.os.Handler.handleCallback(Handler.java:942)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loopOnce(Looper.java:201)
 	at android.os.Looper.loop(Looper.java:288)
 	at android.app.ActivityThread.main(ActivityThread.java:7898)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

I think maybe in somewhere the field `camera` is assigned to null before the Runnable posted in `MainActivity#setKeySelectedForTelegraph` executes.

**Comment by CrazyMarvin** [comment]
Thanks for noticing, @Marukohe! 👍
Are you up to open a fixing PR?

**Comment by Marukohe** [comment]
Sorry, I just know how to trigger the bug, but have no idea how to fix this bug.
When ACTION_DOWN, the camera is open. If ACTION_UP comes in less than 100 milliseconds, a runnable is posted. But when another ACTION_DOWN comes, the camera opens again. If the runnable executes after that, when another ACTION_UP comes, the instance `camera` will be null. 
Maybe you can use `sleep()` function instead of `handler.postDelayed()` for a long time `turnOn`. I don't know if this is appropriate.
@CrazyMarvin

**Comment by fejd** [comment]
Mind if I take a stab at this as part of Hacktoberfest?

**Comment by CrazyMarvin** [comment]
> Mind if I take a stab at this as part of Hacktoberfest?

Thanks for your offer to help.
That would be awesome! 👍

Are you able to reproduce this issue?

**Comment by fejd** [comment]
@CrazyMarvin Yep, I was able to reproduce it.
