### ISSUE TITLE
Crash in fdroid release

### ISSUE THREAD

**Issue by Thewisem** [Crazy-Marvin/Morse#65]
When I installed and opened the app, it keeps on crashing.
Device: SM P555
Achitecture: Armeabi v7a
OS: 7 Nougat

**Comment by CrazyMarvin** [comment]
Does the same happen with the .apk from the [GitHub releases](https://github.com/Crazy-Marvin/Morse/releases/tag/1.6)?

**Comment by Thewisem** [comment]
Yes

**Comment by CrazyMarvin** [comment]
OK, thanks for confirming that.
@FahadSaleem will have a look.

**Comment by Thewisem** [comment]
It crashed on landscape mode

**Comment by Thewisem** [comment]
Ok Hi

**Comment by Thewisem** [comment]
I got a log for the crash

**Comment by Thewisem** [comment]
FATAL EXCEPTION: main
Process: rocks.poopjournal.morse, PID: 31522
java.lang.RuntimeException: Unable to start activity ComponentInfo{rocks.poopjournal.morse/rocks.poopjournal.morse.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3003)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064)
	at android.app.ActivityThread.-wrap14(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
	at rocks.poopjournal.morse.MainActivity.onCreate(MainActivity.java:392)
	at android.app.Activity.performCreate(Activity.java:6977)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
	... 9 more

**Comment by Thewisem** [comment]
Hope this helps

**Comment by HatakeKakashri** [comment]
Thanks for the stack trace @Thewisem. This is part of a larger issue in the App, as covered in #125

**Comment by HatakeKakashri** [comment]
Fixed the crash in https://github.com/Crazy-Marvin/Morse/pull/126
