### ISSUE TITLE
Application srashes after playing a sequence and then trying to play viod.

### ISSUE THREAD

**Issue by OffifialMITX** [Crazy-Marvin/Morse#9]

**Comment by OffifialMITX** [comment]
Looks like this is the error message:

```FATAL EXCEPTION: main
Process: rocks.poopjournal.morse, PID: 17037
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at rocks.poopjournal.morse.MainActivity$5.onClick(MainActivity.java:135)
	at android.view.View.performClick(View.java:5706)
	at android.view.View$PerformClick.run(View.java:22834)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6339)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)```

**Comment by CrazyMarvin** [comment]
We will have a look into it. Thanks for reporting it. 👍

**Comment by CrazyMarvin** [comment]
The crash should be fixed in the [latest release](https://github.com/Crazy-Marvin/Morse/releases/tag/1.3). Can you please check, @OffifialMITX?
